name: "Continuous Integration"
on:
  push:
    # run on pushes to main
    branches:    
      - main
  pull_request:
    # run on pull requests targeting main
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

    - name: Create kind cluster
      uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0

    - name: Deploy From Source
      uses: hiberbee/github-action-skaffold@e3f5dd5659610cb792c6cf32daaa797ea6d89842 # 1.27.0
      with:
        command: run

    - name: Wait For Pods
      timeout-minutes: 20
      run: |
        set -x
        kubectl wait --for=condition=available --timeout=10m deployment/adservice
        kubectl wait --for=condition=available --timeout=10m deployment/cartservice
        kubectl wait --for=condition=available --timeout=10m deployment/checkoutservice
        kubectl wait --for=condition=available --timeout=10m deployment/currencyservice
        kubectl wait --for=condition=available --timeout=10m deployment/emailservice
        kubectl wait --for=condition=available --timeout=10m deployment/frontend
        kubectl wait --for=condition=available --timeout=10m deployment/loadgenerator
        kubectl wait --for=condition=available --timeout=10m deployment/paymentservice
        kubectl wait --for=condition=available --timeout=10m deployment/productcatalogservice
        kubectl wait --for=condition=available --timeout=10m deployment/recommendationservice
        kubectl wait --for=condition=available --timeout=10m deployment/shippingservice
