name: Insecure Workflow Demo

on:
  push:

permissions:
  contents: read

jobs:
  insecure-job:
    runs-on: ubuntu-latest
    permissions: write-all  # ❌ This is insecure on purpose!
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Run something
        run: echo "This is a vulnerable workflow"
